package com.maybank.orsapp.dao;

import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.SQLException;

import org.springframework.jdbc.core.RowMapper;

import com.maybank.orsapp.dto.CardHolderBucketDetailDTO;

public class PrdRdpCardHolderBucketDetailRowMapper implements RowMapper {

	@Override
	public CardHolderBucketDetailDTO mapRow(ResultSet rs, int rowNum) throws SQLException {
		// TODO Auto-generated method stub
		CardHolderBucketDetailDTO obj = new CardHolderBucketDetailDTO();
		
//		private BigDecimal cardholder_point_bucket_id;
		obj.setCardholder_point_bucket_id(rs.getBigDecimal("CARDHOLDER_POINT_BUCKET_ID"));
//		private String cust_no;
		obj.setCust_no(rs.getString("CUST_NO"));
//		private String cust_ic_no;
		obj.setCust_ic_no(rs.getString("CUST_IC_NO"));
//		private String card_type;
		obj.setOrg_no(rs.getString("ORG_NO"));
		obj.setCard_type(rs.getString("CARD_TYPE"));
//		private String card_no;
		obj.setCard_no(rs.getString("CARD_NO"));
//		private String card_exp_date;
		obj.setCard_exp_date(rs.getString("CARD_EXP_DATE"));
//		private String card_post_flag;
		obj.setCard_post_flag(rs.getString("CARD_POST_FLAG"));
//		private String total_points_sign;
		obj.setTotal_points_sign(rs.getString("TOTAL_POINTS_SIGN"));
//		private String total_points_bal;
		obj.setTotal_points_bal(rs.getBigDecimal("TOTAL_POINTS_BAL"));
//		private Integer program_id;
		obj.setProgram_id(rs.getInt("PROGRAM_ID"));
//		private String bucket01_point_sign;
		obj.setBucket01_point_sign(rs.getString("BUCKET01_POINT_SIGN"));
//		private BigDecimal bucket01_point_bal;
		obj.setBucket01_point_bal(rs.getBigDecimal("BUCKET01_POINT_BAL"));
//		private String bucket02_point_sign;
		obj.setBucket02_point_sign(rs.getString("BUCKET02_POINT_SIGN"));
//		private BigDecimal bucket02_point_bal;
		obj.setBucket02_point_bal(rs.getBigDecimal("BUCKET02_POINT_BAL"));
//		private String bucket03_point_sign;
		obj.setBucket03_point_sign(rs.getString("BUCKET03_POINT_SIGN"));
//		private BigDecimal bucket03_point_bal;
		obj.setBucket03_point_bal(rs.getBigDecimal("BUCKET03_POINT_BAL"));
//		private String bucket04_point_sign;
		obj.setBucket04_point_sign(rs.getString("BUCKET04_POINT_SIGN"));
//		private BigDecimal bucket04_point_bal;
		obj.setBucket04_point_bal(rs.getBigDecimal("BUCKET04_POINT_BAL"));
//		private String bucket05_point_sign;
		obj.setBucket05_point_sign(rs.getString("BUCKET05_POINT_SIGN"));
//		private BigDecimal bucket05_point_bal;
		obj.setBucket05_point_bal(rs.getBigDecimal("BUCKET05_POINT_BAL"));
//		private String bucket06_point_sign;
		obj.setBucket06_point_sign(rs.getString("BUCKET06_POINT_SIGN"));
//		private BigDecimal bucket06_point_bal;
		obj.setBucket06_point_bal(rs.getBigDecimal("BUCKET06_POINT_BAL"));
//		private String bucket07_point_sign;
		obj.setBucket07_point_sign(rs.getString("BUCKET07_POINT_SIGN"));
//		private BigDecimal bucket07_point_bal;
		obj.setBucket07_point_bal(rs.getBigDecimal("BUCKET07_POINT_BAL"));
//		private String bucket08_point_sign;
		obj.setBucket08_point_sign(rs.getString("BUCKET08_POINT_SIGN"));
//		private BigDecimal bucket08_point_bal;
		obj.setBucket08_point_bal(rs.getBigDecimal("BUCKET08_POINT_BAL"));
//		private String bucket09_point_sign;
		obj.setBucket09_point_sign(rs.getString("BUCKET09_POINT_SIGN"));
//		private BigDecimal bucket09_point_bal;
		obj.setBucket09_point_bal(rs.getBigDecimal("BUCKET09_POINT_BAL"));
//		private String bucket10_point_sign;
		obj.setBucket10_point_sign(rs.getString("BUCKET10_POINT_SIGN"));
//		private BigDecimal bucket10_point_bal;
		obj.setBucket10_point_bal(rs.getBigDecimal("BUCKET10_POINT_BAL"));
//		private String bucket11_point_sign;
		obj.setBucket11_point_sign(rs.getString("BUCKET11_POINT_SIGN"));
//		private BigDecimal bucket11_point_bal;
		obj.setBucket11_point_bal(rs.getBigDecimal("BUCKET11_POINT_BAL"));
//		private String bucket12_point_sign;
		obj.setBucket12_point_sign(rs.getString("BUCKET12_POINT_SIGN"));
//		private BigDecimal bucket12_point_bal;
		obj.setBucket12_point_bal(rs.getBigDecimal("BUCKET12_POINT_BAL"));
//		private String bucket13_point_sign;
		obj.setBucket13_point_sign(rs.getString("BUCKET13_POINT_SIGN"));
//		private BigDecimal bucket13_point_bal;
		obj.setBucket13_point_bal(rs.getBigDecimal("BUCKET13_POINT_BAL"));
//		private String bucket14_point_sign;
		obj.setBucket14_point_sign(rs.getString("BUCKET14_POINT_SIGN"));
//		private BigDecimal bucket14_point_bal;
		obj.setBucket14_point_bal(rs.getBigDecimal("BUCKET14_POINT_BAL"));
//		private String bucket15_point_sign;
		obj.setBucket15_point_sign(rs.getString("BUCKET15_POINT_SIGN"));
//		private BigDecimal bucket15_point_bal;
		obj.setBucket15_point_bal(rs.getBigDecimal("BUCKET15_POINT_BAL"));
//		private String bucket16_point_sign;
		obj.setBucket16_point_sign(rs.getString("BUCKET16_POINT_SIGN"));
//		private BigDecimal bucket16_point_bal;
		obj.setBucket16_point_bal(rs.getBigDecimal("BUCKET16_POINT_BAL"));
//		private String bucket17_point_sign;
		obj.setBucket17_point_sign(rs.getString("BUCKET17_POINT_SIGN"));
//		private BigDecimal bucket17_point_bal;
		obj.setBucket17_point_bal(rs.getBigDecimal("BUCKET17_POINT_BAL"));
//		private String bucket18_point_sign;
		obj.setBucket18_point_sign(rs.getString("BUCKET18_POINT_SIGN"));
//		private BigDecimal bucket18_point_bal;
		obj.setBucket18_point_bal(rs.getBigDecimal("BUCKET18_POINT_BAL"));
//		private String bucket19_point_sign;
		obj.setBucket19_point_sign(rs.getString("BUCKET19_POINT_SIGN"));
//		private BigDecimal bucket19_point_bal;
		obj.setBucket19_point_bal(rs.getBigDecimal("BUCKET19_POINT_BAL"));
//		private String bucket20_point_sign;
		obj.setBucket20_point_sign(rs.getString("BUCKET20_POINT_SIGN"));
//		private BigDecimal bucket20_point_bal;
		obj.setBucket20_point_bal(rs.getBigDecimal("BUCKET20_POINT_BAL"));
//		private String bucket21_point_sign;
		obj.setBucket21_point_sign(rs.getString("BUCKET21_POINT_SIGN"));
//		private BigDecimal bucket21_point_bal;
		obj.setBucket21_point_bal(rs.getBigDecimal("BUCKET21_POINT_BAL"));
//		private String bucket22_point_sign;
		obj.setBucket22_point_sign(rs.getString("BUCKET22_POINT_SIGN"));
//		private BigDecimal bucket22_point_bal;
		obj.setBucket22_point_bal(rs.getBigDecimal("BUCKET22_POINT_BAL"));
//		private String bucket23_point_sign;
		obj.setBucket23_point_sign(rs.getString("BUCKET23_POINT_SIGN"));
//		private BigDecimal bucket23_point_bal;
		obj.setBucket23_point_bal(rs.getBigDecimal("BUCKET23_POINT_BAL"));
//		private String bucket24_point_sign;
		obj.setBucket24_point_sign(rs.getString("BUCKET24_POINT_SIGN"));
//		private BigDecimal bucket24_point_bal;
		obj.setBucket24_point_bal(rs.getBigDecimal("BUCKET24_POINT_BAL"));
//		private String bucket25_point_sign;
		obj.setBucket25_point_sign(rs.getString("BUCKET25_POINT_SIGN"));
//		private BigDecimal bucket25_point_bal;
		obj.setBucket25_point_bal(rs.getBigDecimal("BUCKET25_POINT_BAL"));
//		private String bucket26_point_sign;
		obj.setBucket26_point_sign(rs.getString("BUCKET26_POINT_SIGN"));
//		private BigDecimal bucket26_point_bal;
		obj.setBucket26_point_bal(rs.getBigDecimal("BUCKET26_POINT_BAL"));
//		private String bucket27_point_sign;
		obj.setBucket27_point_sign(rs.getString("BUCKET27_POINT_SIGN"));
//		private BigDecimal bucket27_point_bal;
		obj.setBucket27_point_bal(rs.getBigDecimal("BUCKET27_POINT_BAL"));
//		private String bucket28_point_sign;
		obj.setBucket28_point_sign(rs.getString("BUCKET28_POINT_SIGN"));
//		private BigDecimal bucket28_point_bal;
		obj.setBucket28_point_bal(rs.getBigDecimal("BUCKET28_POINT_BAL"));
//		private String bucket29_point_sign;
		obj.setBucket29_point_sign(rs.getString("BUCKET29_POINT_SIGN"));
//		private BigDecimal bucket29_point_bal;
		obj.setBucket29_point_bal(rs.getBigDecimal("BUCKET29_POINT_BAL"));
//		private String bucket30_point_sign;
		obj.setBucket30_point_sign(rs.getString("BUCKET30_POINT_SIGN"));
//		private BigDecimal bucket30_point_bal;
		obj.setBucket30_point_bal(rs.getBigDecimal("BUCKET30_POINT_BAL"));
//		private String bucket31_point_sign;
		obj.setBucket31_point_sign(rs.getString("BUCKET31_POINT_SIGN"));
//		private BigDecimal bucket31_point_bal;
		obj.setBucket31_point_bal(rs.getBigDecimal("BUCKET31_POINT_BAL"));
//		private String bucket32_point_sign;
		obj.setBucket32_point_sign(rs.getString("BUCKET32_POINT_SIGN"));
//		private BigDecimal bucket32_point_bal;
		obj.setBucket32_point_bal(rs.getBigDecimal("BUCKET32_POINT_BAL"));
//		private String bucket33_point_sign;
		obj.setBucket33_point_sign(rs.getString("BUCKET33_POINT_SIGN"));
//		private BigDecimal bucket33_point_bal;
		obj.setBucket33_point_bal(rs.getBigDecimal("BUCKET33_POINT_BAL"));
//		private String bucket34_point_sign;
		obj.setBucket34_point_sign(rs.getString("BUCKET34_POINT_SIGN"));
//		private BigDecimal bucket34_point_bal;
		obj.setBucket34_point_bal(rs.getBigDecimal("BUCKET34_POINT_BAL"));
//		private String bucket35_point_sign;
		obj.setBucket35_point_sign(rs.getString("BUCKET35_POINT_SIGN"));
//		private BigDecimal bucket35_point_bal;
		obj.setBucket35_point_bal(rs.getBigDecimal("BUCKET35_POINT_BAL"));
//		private String bucket36_point_sign;
		obj.setBucket36_point_sign(rs.getString("BUCKET36_POINT_SIGN"));
//		private BigDecimal bucket36_point_bal;
		obj.setBucket36_point_bal(rs.getBigDecimal("BUCKET36_POINT_BAL"));
//		private String last_expired_point_sign;
		obj.setLast_expired_point_sign(rs.getString("LAST_EXPIRED_POINT_SIGN"));
//		private BigDecimal last_expired_point_bal;
		obj.setLast_expired_point_bal(rs.getBigDecimal("LAST_EXPIRED_POINT_BAL"));
		
		return obj;
	}

}
