package com.maybank.orsapp.dao;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.sql.Types;

import javax.annotation.PostConstruct;
import javax.sql.DataSource;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.dao.DataAccessException;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.jdbc.core.support.JdbcDaoSupport;
import org.springframework.stereotype.Repository;

@Repository
public class VoidRedemptionDaoImpl extends JdbcDaoSupport implements VoidRedemptionDao {
	
	@Autowired
	@Qualifier("orsDataSource")
	DataSource datasource;
	
	@PostConstruct
	private void initialize() {
		setDataSource(datasource);
	}
	
	public final String UPDATE_CARD_BUCKET = " UPDATE mt_CARDHOLDER_POINT_BUCKET SET "
			+ " TOTAL_POINTS_SIGN=?,TOTAL_POINTS_BAL=?,TRANSFORMED_TOTAL_POINTS_BAL=?,"
			+ " BUCKET01_POINT_SIGN=?,BUCKET01_POINT_BAL=?,BUCKET02_POINT_SIGN=?,BUCKET02_POINT_BAL=?,BUCKET03_POINT_SIGN=?,BUCKET03_POINT_BAL=?,"
			+ " BUCKET04_POINT_SIGN=?,BUCKET04_POINT_BAL=?,BUCKET05_POINT_SIGN=?,BUCKET05_POINT_BAL=?,BUCKET06_POINT_SIGN=?,BUCKET06_POINT_BAL=?,"
			+ " BUCKET07_POINT_SIGN=?,BUCKET07_POINT_BAL=?,BUCKET08_POINT_SIGN=?,BUCKET08_POINT_BAL=?,BUCKET09_POINT_SIGN=?,BUCKET09_POINT_BAL=?,"
			+ " BUCKET10_POINT_SIGN=?,BUCKET10_POINT_BAL=?,BUCKET11_POINT_SIGN=?,BUCKET11_POINT_BAL=?,BUCKET12_POINT_SIGN=?,BUCKET12_POINT_BAL=?,"
			+ " BUCKET13_POINT_SIGN=?,BUCKET13_POINT_BAL=?,BUCKET14_POINT_SIGN=?,BUCKET14_POINT_BAL=?,BUCKET15_POINT_SIGN=?,BUCKET15_POINT_BAL=?,"
			+ " BUCKET16_POINT_SIGN=?,BUCKET16_POINT_BAL=?,BUCKET17_POINT_SIGN=?,BUCKET17_POINT_BAL=?,BUCKET18_POINT_SIGN=?,BUCKET18_POINT_BAL=?,"
			+ " BUCKET19_POINT_SIGN=?,BUCKET19_POINT_BAL=?,BUCKET20_POINT_SIGN=?,BUCKET20_POINT_BAL=?,BUCKET21_POINT_SIGN=?,BUCKET21_POINT_BAL=?,"
			+ " BUCKET22_POINT_SIGN=?,BUCKET22_POINT_BAL=?,BUCKET23_POINT_SIGN=?,BUCKET23_POINT_BAL=?,BUCKET24_POINT_SIGN=?,BUCKET24_POINT_BAL=?,"
			+ " BUCKET25_POINT_SIGN=?,BUCKET25_POINT_BAL=?,BUCKET26_POINT_SIGN=?,BUCKET26_POINT_BAL=?,BUCKET27_POINT_SIGN=?,BUCKET27_POINT_BAL=?,"
			+ " BUCKET28_POINT_SIGN=?,BUCKET28_POINT_BAL=?,BUCKET29_POINT_SIGN=?,BUCKET29_POINT_BAL=?,BUCKET30_POINT_SIGN=?,BUCKET30_POINT_BAL=?,"
			+ " BUCKET31_POINT_SIGN=?,BUCKET31_POINT_BAL=?,BUCKET32_POINT_SIGN=?,BUCKET32_POINT_BAL=?,BUCKET33_POINT_SIGN=?,BUCKET33_POINT_BAL=?,"
			+ " BUCKET34_POINT_SIGN=?,BUCKET34_POINT_BAL=?,BUCKET35_POINT_SIGN=?,BUCKET35_POINT_BAL=?,BUCKET36_POINT_SIGN=?,BUCKET36_POINT_BAL=?,"
			+ " EDITED_BY=?,EDITED_DATETIME=GETDATE()"
			+ " WHERE CARDHOLDER_POINT_BUCKET_ID = ?";

	@Override
	public int updateCardBucket(String TOTAL_POINTS_SIGN, BigDecimal TOTAL_POINTS_BAL,
			BigDecimal TRANSFORMED_TOTAL_POINTS_BAL, String BUCKET01_POINT_SIGN, BigDecimal BUCKET01_POINT_BAL,
			String BUCKET02_POINT_SIGN, BigDecimal BUCKET02_POINT_BAL, String BUCKET03_POINT_SIGN,
			BigDecimal BUCKET03_POINT_BAL, String BUCKET04_POINT_SIGN, BigDecimal BUCKET04_POINT_BAL,
			String BUCKET05_POINT_SIGN, BigDecimal BUCKET05_POINT_BAL, String BUCKET06_POINT_SIGN,
			BigDecimal BUCKET06_POINT_BAL, String BUCKET07_POINT_SIGN, BigDecimal BUCKET07_POINT_BAL,
			String BUCKET08_POINT_SIGN, BigDecimal BUCKET08_POINT_BAL, String BUCKET09_POINT_SIGN,
			BigDecimal BUCKET09_POINT_BAL, String BUCKET10_POINT_SIGN, BigDecimal BUCKET10_POINT_BAL,
			String BUCKET11_POINT_SIGN, BigDecimal BUCKET11_POINT_BAL, String BUCKET12_POINT_SIGN,
			BigDecimal BUCKET12_POINT_BAL, String BUCKET13_POINT_SIGN, BigDecimal BUCKET13_POINT_BAL,
			String BUCKET14_POINT_SIGN, BigDecimal BUCKET14_POINT_BAL, String BUCKET15_POINT_SIGN,
			BigDecimal BUCKET15_POINT_BAL, String BUCKET16_POINT_SIGN, BigDecimal BUCKET16_POINT_BAL,
			String BUCKET17_POINT_SIGN, BigDecimal BUCKET17_POINT_BAL, String BUCKET18_POINT_SIGN,
			BigDecimal BUCKET18_POINT_BAL, String BUCKET19_POINT_SIGN, BigDecimal BUCKET19_POINT_BAL,
			String BUCKET20_POINT_SIGN, BigDecimal BUCKET20_POINT_BAL, String BUCKET21_POINT_SIGN,
			BigDecimal BUCKET21_POINT_BAL, String BUCKET22_POINT_SIGN, BigDecimal BUCKET22_POINT_BAL,
			String BUCKET23_POINT_SIGN, BigDecimal BUCKET23_POINT_BAL, String BUCKET24_POINT_SIGN,
			BigDecimal BUCKET24_POINT_BAL, String BUCKET25_POINT_SIGN, BigDecimal BUCKET25_POINT_BAL,
			String BUCKET26_POINT_SIGN, BigDecimal BUCKET26_POINT_BAL, String BUCKET27_POINT_SIGN,
			BigDecimal BUCKET27_POINT_BAL, String BUCKET28_POINT_SIGN, BigDecimal BUCKET28_POINT_BAL,
			String BUCKET29_POINT_SIGN, BigDecimal BUCKET29_POINT_BAL, String BUCKET30_POINT_SIGN,
			BigDecimal BUCKET30_POINT_BAL, String BUCKET31_POINT_SIGN, BigDecimal BUCKET31_POINT_BAL,
			String BUCKET32_POINT_SIGN, BigDecimal BUCKET32_POINT_BAL, String BUCKET33_POINT_SIGN,
			BigDecimal BUCKET33_POINT_BAL, String BUCKET34_POINT_SIGN, BigDecimal BUCKET34_POINT_BAL,
			String BUCKET35_POINT_SIGN, BigDecimal BUCKET35_POINT_BAL, String BUCKET36_POINT_SIGN,
			BigDecimal BUCKET36_POINT_BAL, String EDITED_BY, BigDecimal CARDHOLDER_POINT_BUCKET_ID) {
		
		int result = 0;
		
		try {
			
			Object[] args = new Object[] {TOTAL_POINTS_SIGN,TOTAL_POINTS_BAL,TRANSFORMED_TOTAL_POINTS_BAL
					,BUCKET01_POINT_SIGN,BUCKET01_POINT_BAL,BUCKET02_POINT_SIGN,BUCKET02_POINT_BAL,BUCKET03_POINT_SIGN,BUCKET03_POINT_BAL
					,BUCKET04_POINT_SIGN,BUCKET04_POINT_BAL,BUCKET05_POINT_SIGN,BUCKET05_POINT_BAL,BUCKET06_POINT_SIGN,BUCKET06_POINT_BAL
					,BUCKET07_POINT_SIGN,BUCKET07_POINT_BAL,BUCKET08_POINT_SIGN,BUCKET08_POINT_BAL,BUCKET09_POINT_SIGN,BUCKET09_POINT_BAL
					,BUCKET10_POINT_SIGN,BUCKET10_POINT_BAL,BUCKET11_POINT_SIGN,BUCKET11_POINT_BAL,BUCKET12_POINT_SIGN,BUCKET12_POINT_BAL
					,BUCKET13_POINT_SIGN,BUCKET13_POINT_BAL,BUCKET14_POINT_SIGN,BUCKET14_POINT_BAL,BUCKET15_POINT_SIGN,BUCKET15_POINT_BAL
					
					,BUCKET16_POINT_SIGN,BUCKET16_POINT_BAL,BUCKET17_POINT_SIGN,BUCKET17_POINT_BAL,BUCKET18_POINT_SIGN,BUCKET18_POINT_BAL
					,BUCKET19_POINT_SIGN,BUCKET19_POINT_BAL,BUCKET20_POINT_SIGN,BUCKET20_POINT_BAL,BUCKET21_POINT_SIGN,BUCKET21_POINT_BAL
					,BUCKET22_POINT_SIGN,BUCKET22_POINT_BAL,BUCKET23_POINT_SIGN,BUCKET23_POINT_BAL,BUCKET24_POINT_SIGN,BUCKET24_POINT_BAL
					,BUCKET25_POINT_SIGN,BUCKET25_POINT_BAL,BUCKET26_POINT_SIGN,BUCKET26_POINT_BAL,BUCKET27_POINT_SIGN,BUCKET27_POINT_BAL
					,BUCKET28_POINT_SIGN,BUCKET28_POINT_BAL,BUCKET29_POINT_SIGN,BUCKET29_POINT_BAL,BUCKET30_POINT_SIGN,BUCKET30_POINT_BAL
					
					,BUCKET31_POINT_SIGN,BUCKET31_POINT_BAL,BUCKET32_POINT_SIGN,BUCKET32_POINT_BAL,BUCKET33_POINT_SIGN,BUCKET33_POINT_BAL
					,BUCKET34_POINT_SIGN,BUCKET34_POINT_BAL,BUCKET35_POINT_SIGN,BUCKET35_POINT_BAL,BUCKET36_POINT_SIGN,BUCKET36_POINT_BAL
					,EDITED_BY,CARDHOLDER_POINT_BUCKET_ID};

			int[] types = new int[] {Types.VARCHAR,Types.NUMERIC,Types.NUMERIC
					,Types.VARCHAR,Types.NUMERIC,Types.VARCHAR,Types.NUMERIC,Types.VARCHAR,Types.NUMERIC
					,Types.VARCHAR,Types.NUMERIC,Types.VARCHAR,Types.NUMERIC,Types.VARCHAR,Types.NUMERIC
					,Types.VARCHAR,Types.NUMERIC,Types.VARCHAR,Types.NUMERIC,Types.VARCHAR,Types.NUMERIC
					,Types.VARCHAR,Types.NUMERIC,Types.VARCHAR,Types.NUMERIC,Types.VARCHAR,Types.NUMERIC
					,Types.VARCHAR,Types.NUMERIC,Types.VARCHAR,Types.NUMERIC,Types.VARCHAR,Types.NUMERIC
					
					,Types.VARCHAR,Types.NUMERIC,Types.VARCHAR,Types.NUMERIC,Types.VARCHAR,Types.NUMERIC
					,Types.VARCHAR,Types.NUMERIC,Types.VARCHAR,Types.NUMERIC,Types.VARCHAR,Types.NUMERIC
					,Types.VARCHAR,Types.NUMERIC,Types.VARCHAR,Types.NUMERIC,Types.VARCHAR,Types.NUMERIC
					,Types.VARCHAR,Types.NUMERIC,Types.VARCHAR,Types.NUMERIC,Types.VARCHAR,Types.NUMERIC
					,Types.VARCHAR,Types.NUMERIC,Types.VARCHAR,Types.NUMERIC,Types.VARCHAR,Types.NUMERIC
					
					,Types.VARCHAR,Types.NUMERIC,Types.VARCHAR,Types.NUMERIC,Types.VARCHAR,Types.NUMERIC
					,Types.VARCHAR,Types.NUMERIC,Types.VARCHAR,Types.NUMERIC,Types.VARCHAR,Types.NUMERIC
					,Types.VARCHAR,Types.BIGINT};

			result = getJdbcTemplate().update(UPDATE_CARD_BUCKET, args, types);

		} catch (DuplicateKeyException ex) {
			ex.printStackTrace();
		} catch (DataAccessException ex) {
			ex.printStackTrace();
		}
		return result;	
		
	}

	@Override
	public int updateApPointTxn(Long pointTxnId, String reversalReason) {
		Connection conn = null;
		PreparedStatement  stmt = null;
		Timestamp now = new Timestamp(System.currentTimeMillis());
		int rows = 0;
		try {
			
			String sql = "UPDATE [dbo].[ap_POINT_TXN] " +
		            "SET [REDEMPTION_STATUS] = ?, "
		            + "[REVERSAL_BY] = ?, "
		            + "[REVERSAL_DATETIME] = ?, "
		            + "[REVERSAL_REASON] = ?, "
		            + "[EDITED_BY] = ?, "
		            + "[EDITED_DATETIME] = ? "
		            + "WHERE [POINT_TXN_ID] = ?";
			
			conn = datasource.getConnection();
			stmt = conn.prepareStatement(sql);
			stmt.setString(1, "V");
			stmt.setString(2, "System User");
			stmt.setTimestamp(3, now);
			stmt.setString(4, reversalReason);
			stmt.setString(5, "System User");
			stmt.setTimestamp(6, now);
			stmt.setLong(7, pointTxnId);
			rows = stmt.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
		}catch (Exception e) {
			e.printStackTrace();
		}finally {
			 try {
				 if(stmt !=null)
					 conn.close();
			} catch (SQLException e) {
				e.printStackTrace();
			}
		}
		
		return rows;
	}
}
